spring:
  application:
    name: event-gateway
  datasource:
    url: jdbc:h2:mem:event-gateway-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

account-service:
  base-url: ${ACCOUNT_SERVICE_BASE_URL:http://localhost:8081}

logging:
  structured:
    format:
      console: logstash
    json:
      add:
        service: event-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-components: always
      show-details: always

server:
  port: 8080
